# Generated by Django 5.1 on 2024-08-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_debt_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditor',
            old_name='contact',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='creditor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
