# Generated by Django 5.1 on 2024-08-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_credit_creditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(choices=[('pcs', 'Pcs'), ('box', 'Box'), ('ctn', 'Carton'), ('ltr', 'Ltr'), ('kg', 'Kg'), ('pair', 'Pair'), ('bag', 'Bag'), ('dozen', 'Dozen'), ('gram', 'Gram'), ('roll', 'Roll')], max_length=100),
        ),
    ]
