# Generated by Django 5.1 on 2024-08-31 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, choices=[('pcs', 'Pcs'), ('box', 'Box'), ('ctn', 'Carton'), ('ltr', 'Ltr'), ('kg', 'Kg'), ('pair', 'Pair'), ('bag', 'Bag'), ('dozen', 'Dozen'), ('gram', 'Gram'), ('roll', 'Roll')], max_length=100, null=True),
        ),
    ]
