# Generated by Django 5.1 on 2024-09-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='notes',
        ),
    ]
