# Generated by Django 5.1 on 2024-09-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_sale_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refunded_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
