# Generated by Django 5.1 on 2024-09-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storedebtpayments', to='store.store'),
        ),
    ]
