# Generated by Django 5.1 on 2024-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_seller_created_at_alter_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='purchase_price_at_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='selling_price_at_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
